\connect thesis;
SET search_path TO thesis;

INSERT INTO thesis.process (id, inspector_id, location_id, contact_id, title, type, priority, version, created_at_utc, created_by, last_modified_at_utc, last_modified_by) VALUES (1, 1, 2, 1, null, 'NORMAL', 'NORMAL', 1, '2020-05-09 20:43:47.910000', 'IMPORT', null, null);
INSERT INTO thesis.process (id, inspector_id, location_id, contact_id, title, type, priority, version, created_at_utc, created_by, last_modified_at_utc, last_modified_by) VALUES (2, 1, 3, 2, null, 'NORMAL', 'NORMAL', 1, '2020-05-09 20:43:47.910000', 'IMPORT', null, null);
INSERT INTO thesis.process (id, inspector_id, location_id, contact_id, title, type, priority, version, created_at_utc, created_by, last_modified_at_utc, last_modified_by) VALUES (3, 1, 4, 2, null, 'NORMAL', 'NORMAL', 1, '2020-05-09 20:43:47.910000', 'IMPORT', null, null);
INSERT INTO thesis.process (id, inspector_id, location_id, contact_id, title, type, priority, version, created_at_utc, created_by, last_modified_at_utc, last_modified_by) VALUES (4, 1, 5, 1, null, 'NORMAL', 'NORMAL', 1, '2020-05-09 20:43:47.910000', 'IMPORT', null, null);

INSERT INTO thesis.process (id, inspector_id, location_id, contact_id, title, type, priority, version, created_at_utc, created_by, last_modified_at_utc, last_modified_by) VALUES (5, 2, 6, 3, null, 'NORMAL', 'NORMAL', 1, '2020-05-09 20:43:47.910000', 'IMPORT', null, null);
INSERT INTO thesis.process (id, inspector_id, location_id, contact_id, title, type, priority, version, created_at_utc, created_by, last_modified_at_utc, last_modified_by) VALUES (6, 2, 7, 4, null, 'NORMAL', 'NORMAL', 1, '2020-05-09 20:43:47.910000', 'IMPORT', null, null);
INSERT INTO thesis.process (id, inspector_id, location_id, contact_id, title, type, priority, version, created_at_utc, created_by, last_modified_at_utc, last_modified_by) VALUES (7, 2, 8, 5, null, 'NORMAL', 'NORMAL', 1, '2020-05-09 20:43:47.910000', 'IMPORT', null, null);
INSERT INTO thesis.process (id, inspector_id, location_id, contact_id, title, type, priority, version, created_at_utc, created_by, last_modified_at_utc, last_modified_by) VALUES (8, 2, 9, 3, null, 'NORMAL', 'NORMAL', 1, '2020-05-09 20:43:47.910000', 'IMPORT', null, null);