\connect thesis;
SET search_path TO thesis;

INSERT INTO thesis.appointment (id, process_id, description, date, travel_duration_sec, start_time, appointment_duration_sec, finished, version, created_at_utc, created_by, last_modified_at_utc, last_modified_by) VALUES (1, 1, null, CURRENT_DATE, null, null, 900, false, 1, '2020-05-09 20:45:10.979000', 'IMPORT', null, null);
INSERT INTO thesis.appointment (id, process_id, description, date, travel_duration_sec, start_time, appointment_duration_sec, finished, version, created_at_utc, created_by, last_modified_at_utc, last_modified_by) VALUES (2, 2, null, CURRENT_DATE, null, null, 900, false, 1, '2020-05-09 20:45:10.979000', 'IMPORT', null, null);
INSERT INTO thesis.appointment (id, process_id, description, date, travel_duration_sec, start_time, appointment_duration_sec, finished, version, created_at_utc, created_by, last_modified_at_utc, last_modified_by) VALUES (3, 3, null, CURRENT_DATE, null, null, 900, false, 1, '2020-05-09 20:45:10.979000', 'IMPORT', null, null);
INSERT INTO thesis.appointment (id, process_id, description, date, travel_duration_sec, start_time, appointment_duration_sec, finished, version, created_at_utc, created_by, last_modified_at_utc, last_modified_by) VALUES (4, 4, null, CURRENT_DATE, null, null, 900, false, 1, '2020-05-09 20:45:10.979000', 'IMPORT', null, null);

INSERT INTO thesis.appointment (id, process_id, description, date, travel_duration_sec, start_time, appointment_duration_sec, finished, version, created_at_utc, created_by, last_modified_at_utc, last_modified_by) VALUES (5, 5, null, CURRENT_DATE, null, null, 900, false, 1, '2020-05-09 20:45:10.979000', 'IMPORT', null, null);
INSERT INTO thesis.appointment (id, process_id, description, date, travel_duration_sec, start_time, appointment_duration_sec, finished, version, created_at_utc, created_by, last_modified_at_utc, last_modified_by) VALUES (6, 6, null, CURRENT_DATE, null, null, 900, false, 1, '2020-05-09 20:45:10.979000', 'IMPORT', null, null);
INSERT INTO thesis.appointment (id, process_id, description, date, travel_duration_sec, start_time, appointment_duration_sec, finished, version, created_at_utc, created_by, last_modified_at_utc, last_modified_by) VALUES (7, 7, null, CURRENT_DATE, null, null, 900, false, 1, '2020-05-09 20:45:10.979000', 'IMPORT', null, null);
INSERT INTO thesis.appointment (id, process_id, description, date, travel_duration_sec, start_time, appointment_duration_sec, finished, version, created_at_utc, created_by, last_modified_at_utc, last_modified_by) VALUES (8, 8, null, CURRENT_DATE, null, null, 900, false, 1, '2020-05-09 20:45:10.979000', 'IMPORT', null, null);